---
title: "Analyse factorielle"
---

## Exercice 2.1

Les données `sondage_entreprise` contiennent les résultats d'un sondage effectué par une compagnie auprès de ses employés. Le but de l'exercice est d'ajuster un modèle d'analyse factorielle exploratoire (avec rotation varimax) aux données.

1. Produisez des statistiques descriptives pour les variables `q8` à `q17`
2. Combien y a-t-il de répondants? Déterminez si ce nombre est suffisant pour effectuer une analyse factorielle.
3. Utilisez la méthode d'estimation par composantes principales et le critère de Kaiser pour ajuster le modèle d'analyse factorielle. Combien de facteurs serait-il raisonnable de retenir?
4. Répétez l'exercice, cette fois avec la méthode du maximum de vraisemblance
    - Est-ce qu'un de ces modèles ajustés est un cas de quasi-Heywood?
    - Combien de facteurs les critères d'information recommendent-ils?
    - Si vous ajoutez des facteurs, est-ce que votre interprétation change?
5. Créez des échelles et vérifiez leur cohérence interne. 

 
## Exercice 2.2
 
Effectuez une analyse factorielle exploratoire des données `aerien_facto`: cette base de données contient  toutes les questions en lien avec la satisfaction de la base de données `aerien`. Les valeurs 0 correspondent à des champs non applicables (une forme de données manquantes).

1. Ajustez un modèle avec la méthode des composantes principales et une rotation varimax. 
    - Combien de facteurs le critère des valeurs propres suggère-t-il?
    - Combien de facteurs le diagramme d'éboulis suggère-t-il?
    - Interprétez les chargements obtenus suite à la rotation. Commentez sur l'interprétabilité de ces derniers.
    - En utilisant un nombre adéquat de facteurs et un point de coupure approprié, formez des échelles et vérifiez leur cohérence interne.
2.  Répétez l'exercice, mais en utilisant cette fois la méthode du maximum de vraisemblance pour ajuster le modèle. 
    - Qu'arrive-t-il lorsque vous augmentez le nombre de facteurs? Formulez une hypothèse de travail pour expliquer ce comportement.

