project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "diapos/*.html"
    - "diapos/*.pdf"
    - "diapos/img/"
    - "diapos/libs/"
    - "diapos/css/"
    - "diapos/*_files/"


# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/math60602.bib
csl: files/bib/apa.csl

toc-title: "Table des matières"
website:
  title: "Analyse multidimensionnelle appliquée"
  site-url: "https://lbelzile.github.io/math60602"
  description-meta: "Formation de base en traitement de données multidimensionnelles. Compréhension intuitive, interprétation et utilisation de plusieurs techniques statistiques à l'aide de logiciels appropriés."

  navbar:
    pinned: true
    background: "#003C71"
    right:
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Horaire"
        file: horaire.qmd
      - text: "Contenu"
        file: contenu/index.qmd
      - text: "Évaluations"
        file: evaluations/index.qmd
      - text: "Exercices"
        file: exercices/index.qmd
      - text: "Notes"
        href: "https://lbelzile.github.io/math60602"
      - icon: wechat
        href: "https://piazza.com/hec.ca/fall2022/math60602/home"
        aria-label: Piazza
      - icon: inbox-fill
        href: "https://lbelzile.github.io/hecmulti"
        aria-label: Données
      	 
 
  sidebar:
    - title: "Contenu"
      style: "docked"
      search: false
      foreground: "#003C71"
      contents:
        - text: "Contenu"
          file: contenu/index.qmd
        - section: "Ressources"
          contents:
            - text: "Ressources **R**"
              file: contenu/ressourcesR.qmd
            - text: "Installer **R** et RStudio"
              file: contenu/installation.qmd
        - section: "Matériel pédagogique"
          contents:
            - text: "1: Introduction"
              file: contenu/01-contenu.qmd
            - text: "2: Programmation en **R**"
              file: contenu/02-contenu.qmd
            - text: "3: Réduction de la dimension"
              file: contenu/03-contenu.qmd
 

    - title: "Devoirs"
      style: "docked"
      search: false
      foreground: "#ad1aac"
      contents:
        - text: "Notation"
          file: evaluations/index.qmd
        - section: "Devoirs"
          contents:
            - evaluations/01-devoir.qmd
        #    - evaluations/02-devoir.qmd
        #    - evaluations/03-devoir.qmd
        #    - evaluations/04-devoir.qmd
        #    - evaluations/05-devoir.qmd
        #    - evaluations/06-devoir.qmd
    - title: "Exercices"
      style: "docked"
      search: false
      foreground: "#003C71"
      contents:
        - text: "Exercices"
          file: exercices/index.qmd
        - text: "Analyse exploratoire"
          file: exercices/01-exercice.qmd
        - text: "Analyse factorielle"
          file: exercices/02-exercice.qmd


  page-footer:
    left: |
      Contenu {{< fa brands creative-commons >}} {{< var course.copyright_year >}} par [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}); canevas du site par [Dr. Andrew Heiss](https://www.andrewheiss.com/) sous [licence MIT](https://mit-license.org/) <br>
      Tout le contenu du site (hors notes) est distribué sous licence {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Fabriqué avec {{< fa brands r-project >}} et [Quarto](https://quarto.org/)<br>
      [Code source sur {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: github
