---
title: "Devoir 2"
---

Les observations de la base de données [`bjffacto`](https://lbelzile.github.io/hecmulti/reference/bjffacto.html) sont tirées de l'article @Bastian:2014 et sont rattachées à une expérience en psychologie visant à corroborer l'hypothèse qu'il y a une coopération accrue entre individus sujets à une expérience traumatisante. La moitié des participant(e)s a dû plonger sa main dans un bain d'eau glacé, tandis que l'autre moitié a dû faire la même chose dans un bain d'eau tiède; les deux groupes devaient ensuite faire un jeu visant à identifier leur niveau de coopération.

La variable `condition` indique le groupe expérimental (zéro pour groupe contrôle, un pour douleur).

**Indication**: utilisez la matrice de *corrélation* pour effectuer l'analyse factorielle.

1. Pourquoi n'est-il pas nécessaire de standardiser les variables avant de procéder à la création d'échelles dans cet exemple? Justifiez votre réponse.
2. Effectuez une analyse factorielle exploratoire à l'aide de la méthode des composantes principales. 
    a. Combien de facteurs le critère de Kaiser (valeurs propres) suggère-t-il?
    b. Produisez un diagramme d'éboulis et rapportez ce dernier. Commentez sur le choix de facteurs selon le critère de Cattel (coude), au vu de la taille de l'échantillon.
    c. Quel pourcentage de la variance totale est expliquée par votre combinaison de facteurs?^[Vous pouvez extraire les variances des composantes principales à partir de `eigen(...)$values`.]
3. Répétez la procédure, cette fois avec la méthode d'estimation par maximum de vraisemblance. 
    a. Rapportez les valeurs des critères d'information (AIC et BIC) pour $m=2, \ldots, 6$ facteurs dans un tableau. 
    b. Quel nombre optimal de facteurs ces différents critères retournent-ils? 
    c. Y a-t-il un problème avec la solution de l'un d'entre eux?
4. Comparez les regroupements obtenus avec les deux méthodes d'estimation (composantes principales et maximum de vraisemblance) pour la solution à $k=2$ facteurs: est-ce que les regroupements sont semblables (c'est-à-dire, est-ce que les variables retournées dans les regroupements sont associées aux mêmes facteurs)?^[Il est possible que les signes soient différents, ou que l'ordre des facteurs soit différent. Cela ne devrait pas affecter votre conclusion.]
5.  Étiquetez les facteurs obtenus avec la méthode des composantes principales et $k=2$ facteurs. Expliquez brièvement leur signification. 
6. 
   a. Créez des échelles à partir des facteurs. Utilisez le seuil de coupure $c=0.4$ pour les chargements pour déterminer si une variable fait partie d'une échelle. 
   b. Estimez la cohérence interne des échelles à l'aide du $\alpha$ de Cronbach et commentez.
7. Retournez un tableau de statistiques descriptives (moyenne et écart-type uniquement) des échelles, par condition expérimental (`condition`). Arrondissez à deux chiffres après la virgule et commentez sur les différences entre groupes, le cas échéant.

Vous devez remettre 

- un rapport au format PDF et 
- votre code **R** ou un fichier Rmarkdown (extensions `.R` ou `.Rmd`)

Nommez ces derniers selon la convention `d2_matricule.pdf`, `d2_matricule.R`, etc.
