---
title: "Analyse multidimensionnelle appliquée"
lang: fr
author: "Léo Belzile, HEC Montréal"
subtitle: "Survol des contenus du cours"
date: today
date-format: "[Diapositives compilées le] dddd MMM D, YYYY"
eval: true
cache: true
echo: true
standalone: true
width: 1200
height: 900
format:
  revealjs:
    slide-number: true
    html-math-method: mathjax
    preview-links: auto
    theme: [simple, hecmontreal.scss]
    title-slide-attributes:
      data-background-color: "#00aec7"
    logo: "figures/logo_hec_montreal_bleu_web.png"
---


```{r}
#| include: false

hecbleu <- c("#002855")
fcols <- c(gris = "#888b8d",
           bleu = "#0072ce",
           aqua = "#00aec7",
           vert = "#26d07c",
           rouge = "#ff585d",
           rose = "#eb6fbd",
           jaune = "#f3d03e")
pcols <- c(gris = "#d9d9d6",
           bleu = "#92c1e9",
           agua = "#88dbdf",
           vert = "#8fe2b0",
           rouge = "#ffb1bb",
           rose = "#eab8e4",
           jaune = "#f2f0a1")
library(ggplot2)
theme_set(theme_classic())
library(patchwork)
knitr::opts_chunk$set(fig.retina = 3, collapse = TRUE)
options(digits = 3, width = 75)
```

# Domaines d'application


- Acquisition, fidélisation et rétention de clientèle
- Vente croisée et vente incitative
- Segmentation, médecine personnalisée
- Prévention de la fraude, automatisation de décisions de crédit, prévision de pertes oou de faillites

**Secteurs d'activité**: Toute entreprise accumulant une grande quantité de données, notamment

- Commerce de détail
- Télécommunications
- Institutions financières (banques et assureurs)

# Modèles de prédiction

Construire un modèle prédictif pour un objectif précis à l'aide d'un grand ensemble de variables explicatives (données transactionnelles, information sur le client, données externes, etc.)

**Exemples**:

- Détecter les faillites des clients (ou des entreprises)
- Cibler les clients qui seront intéressés par une offre promotionnelle
- Détecter les fraudes (par carte de crédit ou dans les rapports de revenus)
- Prévoir d'avance si un client va nous quitter

# Régression logistique

Modèle de régression pour variables réponses binaires (0/1) ou catégorielles.

- accepter ou refuser une offre promotionnelle
- quitter une enterprise (rétention de personnelle)
- vote lors d'une élection

# Exemples de régression logistique 

- Une compagnie de télécommunication veut déterminer parmi les détenteurs du produit A, ceux qui sont les plus propices à acheter le produit B (modèle de vente croisée).
- Suite à une campagne de commercialisation, une compagnie veut déterminer les caractéristiques qui distinguent les clients qui ont accepté l'offre de ceux qui l'ont refusée.
- Une banque veut déterminer si un client est à risque de cesser le remboursement de son prêt ou non.
- Une compagnie d'assurance veut estimer la probabilité pour ses clients de faire une réclamation dans la prochaine année.

# Données manquantes

Une agence de voyage aimerait faire la promotion d'un forfait tout inclus dans le sud
pour la famille. Pour bien cibler son offre, l'agence doit envoyer la promotion à ses clients qui ont des enfants. Toutefois, cette information n'est pas toujours disponible.

# Cause des données manquantes

- Refus de répondre à une question d'un sondage.
- L'information sur les clients est incomplète.
- Le client ne détient pas d'information pour certaines caractéristiques (exemple : client qui n'a jamais eu de crédit).

Par défaut, les logiciels suppriment les observations pour lesquelles une valeur est manquante. Ignorer ces personnes et faire l'analyse des cas complets mène à des estimations biaisés et invalide l'inférence statistique.

# Analyse de survie

Une compagnie de télécommunication est intéressée au temps qu'un client
demeure abonné au service de téléphonie mobile.

Au moment de l'analyse, l'historique de la base de données indiquent le moment où certaines personnes se sont désabonnées, mais d'autres sont encore clients actifs.

- Temps avant le prochain achat d'un client.
- Temps avant la faillite d'une entreprise (ou d'un particulier)
- Temps qu'un employé demeure au service de la compagnie.

# Segmentation et analyse de regroupements

Un organisme de charité aimerait classer ses donateurs dans des groupes selon leurs caractéristiques (âge, montant des dons, fréquence des dons, canal de communication, ...)

L'analyse de regroupements vise à créer des sous-groupes qui partagent de même caractéristiques.

- Quels sont les caractéristiques des donateurs et donatrices les plus généreux?
- Ces derniers sont-ils représentatifs de la population québécoise?
