---
title: "Introduction"
---

## Contenu

- Plan de cours et objectifs d'apprentissage
- Survol du contenu du cours
- Considérations éthiques: discussion de l'article [*How Companies Learn Your Secrets*](https://www.nytimes.com/2012/02/19/magazine/shopping-habits.html), via [ZoneCours](https://zonecours2.hec.ca/access/content/group/MATH60602.A2022/NYT_How_companies_learn_your_secrets.pdf)
- Analyse exploratoire des données
- Introduction aux données manquantes

## Avant le cours

- Se familiariser avec le [plan de cours](/syllabus), le [contenu des séances](/contenu/), le [forum en ligne](https://piazza.com/hec.ca/fall2023/math60602/home), les [exercices](/exercices) et les [devoirs](/evaluations/).
- S'inscrire sur [Piazza](http://piazza.com/hec.ca/fall2023/math60602).


## Lectures

:::{.callout-warning}
Idéalement, je vous encourage à lire les notes de cours avant de venir en classe. Cela vous permettra de venir avec des questions en tête et de demander des éclaircissements.
:::

- {{< fa book >}} [Chapitre sur l'analyse exploratoire des données](https://lbelzile.github.io/math60602/analyseexploratoire.html)
- {{< fa book >}} [Chapitre sur les données manquantes](https://lbelzile.github.io/math60602/donneesmanquantes.html), partie 

## Diapositives 


- {{< fa file >}} [Survol des sujets](/diapos/MATH60602-diapos0.pdf)
- {{< fa file >}} [Graphiques et analyse exploratoire](/diapos/MATH60602-diapos1.pdf)

<!--
## Activités

**[Atelier de visualisation](/files/graphiques.zip)**: vous devrez analyser des graphiques en équipes et donner une appréciation d'ensemble de l'efficacité du graphique pour transmettre une histoire en plus d'identifier les informations suivantes:

- les variables
- la dimension à laquelle elles sont affectées (axes des abscisse, axe des ordonnées, couleur, forme, taille, etc.)
- le type de représentation (diagramme en bâton, nuage de point, en violon, etc.)
- les forces et faiblesses des représentations graphiques (absence de légende, problème de lisibilité, etc.)

-->


## Objectifs d'apprentissage

- Réaliser une analyse exploratoire et formuler des questions en lien avec une base de données.
- Décomposer un graphique en éléments et déterminer la représentation adéquate pour une question donnée.
- Déterminer les méthodes appropriées selon le type de données manquantes
- Calculer le taux de cas manquants


## Ressources complémentaires

- [Chapitre 7 de **R for Data Science** par Garrett Grolemund et Hadley Wickham](https://r4ds.had.co.nz/exploratory-data-analysis.html)
- [Chapitre 1 de *Data Visualization: A practical introduction* par Kieran Healy](https://socviz.co/lookatdata.html#lookatdata)
- [Feuille aide-mémoire de DataViz](https://policyviz.com/2018/08/07/dataviz-cheatsheet/)

